-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 10, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 0.729 s <<< FAILURE! - in TestSuite
setUp(test.cases.LoginAppValidation)  Time elapsed: 0.597 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Connection refused
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'IN-LYQPY64XJ9', ip: '2407:ff00:12:1ea:8c99:e3cb:2e95:9e55%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.6.4', java.version: '21.0.2'
Driver info: driver.version: AppiumDriver
	at test.cases.LoginAppValidation.setUp(LoginAppValidation.java:61)
Caused by: java.net.ConnectException: Connection refused
	at test.cases.LoginAppValidation.setUp(LoginAppValidation.java:61)

